#! /bin/bash

: <<=cut
=pod

=head1  NAME

  inititalize - Initialize this example repository

=head1 USAGE

  initialize --fin=<fin cmd> <--print=Hhb> <--delete> --do=sys,users,collections

=head1 OPTIONS

You probably just need to run ./initialize --fin='node ~/fin-cli/lib' --all

=over 4	

=item B<--fin=> I<cmd>
 Set the fin command line argument.  if not set, will try fin.  Currently you may need something like.
 B<--fin='node /home/quinn/fin-cli/lib'>.  You can also set options here as in
 B<--fin='node /home/quinn/fin-cli/lib -P Hhb'>.  If you want to debug, you can say B<--fin=echo> and see 
 the fin commands used.

=item B<--print=> I<HBhb>
    Set the printing parameter for fin.  By default it is I<Hhb>

=item B<--delete>
Delete an item before building it.

=item B<--do=> I<sys,users,collections>
Specify what to inititialize; options include sys,users,collections. Default is sys,users,collections.

=back
=cut


# This example assumes that you already have your fin-cli setup with a user with administrative permissions.
fin_delete() {
     OPTS=`getopt -o f  --long force,tombstone -n 'inf4 delete' -- "$@"` 
    if [ $? != 0 ] ; then echo "Bad delete options." >&2 ; exit 1 ; fi
    eval set -- "$OPTS"
    tombstone=
    while true; do
    	case $1 in
	    -f | --force | --tombstone) tombstone=1; shift;;
	    --) shift; break;;
    	*) break;;
    	esac
    done
    if [[ -n $1 ]]; then
        $fin http delete $1;   
        if [[ -n $tombstone ]]; then
            $fin http delete $1/fcr:tombstone
        fi
    fi
}

fin_mkdir() {
    OPTS=`getopt -o @: --long file:,relation:,resource: -n 'mkdir [options]' -- mkdir "$@"` 
    if [ $? != 0 ] ; then echo "Bad mkdir options." >&2 ; exit 1 ; fi
    eval set -- "$OPTS"
    local a="<> a ldp:BasicContainer"
    local file=
    local relation=
    local resource='..'
    while true; do
    	case $1 in
        -@ | --file ) file=$2; shift 2;;
		--relation) relation=$2; shift 2;;
	    --resource) resource=$2; shift 2;;
	    --) shift; break;;
    	*) break;;
    	esac
    done
    shift;

    if [[ -n $1 ]]; then
        if [[ -n $file ]]; then 
            $fin http put $opts -@ $file $1
        else
            if [[ -n $relation ]] ; then
                a="<> a ldp:DirectContainer; ldp:hasMemberRelation $relation; ldp:membershipResource $resource ."
            fi
            $fin http put $opts -t "$a" $1
        fi
    fi
}

auth_add() {
     OPTS=`getopt --long acl:,mode:,to:,agent:,group: -n 'auth [options]' -- auth "$@"` 
    if [ $? != 0 ] ; then echo "Bad auth_add options." >&2 ; exit 1 ; fi
    eval set -- "$OPTS"
    local mode="acl:Read"
    local to=
    local agent="foaf:Agent"
    local group=
    local authname=
    local auth=
    local slug=
    local acl=.acl
    while true; do
    	case $1 in
        --acl) acl=$2; shift 2;;
	    --mode) mode=$2; shift 2;;
        --to) to=$2; shift 2;;
	    --agent) agent=$2; shift 2;;
	    --group) mode=$2; shift 2;;
        *) break;;
    	esac
    done
    shift;
    if [[ -n $agent ]] ; then
        auth+="acl:agent $agent ; "
    fi
    if [[ -n $group ]]; then
        auth+="acl:agentClass $group ;"
    fi;
    if [[ -n $1 ]]; then
        slug="-H Slug:$1"
    fi
    $fin http post $opts $acl -t "<> a acl:Authorization; $auth acl:accessTo $to; acl:mode $mode ." $slug
}

acl_create() {
    OPTS=`getopt --long dir:,label:,default -n 'acl [options]' -- acl "$@"` 
    if [ $? != 0 ] ; then echo "Bad acl options." >&2 ; exit 1 ; fi
    eval set -- "$OPTS"
    local dir=
    local rdir=
    local adir=
    local label='Local Access Control'
    local default=
    while true; do
    	case $1 in
        --default) default=1; shift;;
        --label) label=$2; shift 2;;
	    --dir) dir=$2; shift 2;;
        *) break;;
    	esac
    done
    if [[ -n $dir ]]; then
        adir=`readlink -m $dir/.acl`
        rdir=`readlink -m $R/$dir`
        $fin http put $opts -t "<> a ldp:BasicContainer,webac:Acl; rdfs:label \"$label\" . " $adir;
        if [[ -n $default ]]; then
            auth_add --acl=$adir --agent=foaf:Agent --mode=acl:Read --to="<$rdir>"
        fi
        # Reset adir for full path
        adir=`readlink -m $R/$dir/.acl`
        $fin http patch $opts $dir -t "insert {<> acl:accessControl <${adir}> .} where {}" 
    fi
 }


: <<=cut
=pod
=head 2 add_user
Passed the user_id
=cut
add_user () {
    local u=$1
    fin_mkdir /user/$u
    # Add to system so Even if user removes local .acl, they still have access.
    auth_add --acl=/.acl --agent=user:$u --mode=acl:Read,acl:Write --to="<$R/user/$u>"
    # Create a user definable .acl for this user.
    acl_create --dir=/user/$u
    # Add to system so Even if user removes local .acl, they still have access.
    auth_add --acl=/.acl --agent=user:$u --mode=acl:Read,acl:Write --to="<$R/user/$u>"
    auth_add --acl=/.acl --agent="\"$u\"" --mode=acl:Read,acl:Write --to="<$R/user/$u>"

    # Add to Read/Write for user, Read for users
    auth_add --acl=/user/$u/.acl --agent=user:$u --mode=acl:Read,acl:Write --to="<$R/user/$u>"
    auth_add --acl=/user/$u/.acl --agent="\"$u\"" --mode=acl:Read,acl:Write --to="<$R/user/$u>"
    auth_add --acl=/user/$u/.acl --agent=foaf:Agent --mode=acl:Read --to="<$R/user/$u>"
}

: <<=cut
=pod
=head 2 add_group
Passed the user_id (as in user/quinn).  Creates a new user in the appropriate location
=cut
add_group () {
    local u=$1
    local file
    if [[ -n $2 ]]; then
        file="--file=$2"
    fi 
    fin_mkdir $file /collection/$u
    # Create a user definable .acl for this user.
    acl_create --dir=/collection/$u --default
    fin_mkdir /collection/$u/group
    $fin http put /collection/$u/group/admin -t '<> a foaf:Group ; foaf:member "quinn","jrmerz" .' 
    # Add to Read/Write for user, Read for users
    auth_add --acl=/collection/$u/.acl --group="<$R/collection/$u/group/admin>" --mode=acl:Read,acl:Write --to="<$R/collection/$u>"
    auth_add --acl=/collection/$u/.acl --agent=foaf:Agent --mode=acl:Read --to="<$R/collection/$u>"
    # members is where the data goes.
    fin_mkdir --relation=pcdm:hasMember --resource="<$R/collection/$u>" /collection/$u/members
}

: <<=cut
=pod
This is the main initialization program. Eventually, the above functions will be gone, and 
we will just have
=cut

add_eastman() {
    local d b i s
    local u='eastman-example'
    for f in `find collection/eastman-example -type f -name \*.tif`; do
        echo $f
        d=`dirname $f`;
        b=`basename $f`;
        i=`basename $f .tif`;
        n=$d/members/$i
        mime=`file --mime-type -b $f`;
        $fin http put -H "Content-Type:$mime" -@ $f $n
        s=$f.ttl;
        if [[ -f $s ]] ; then
            ttl=$(sed -e "s|<>|<$R/collection/$u/members/$i>|g" < $s | tr -d '\n')
            $fin http put $opts -H prefer:return=minimal -t "$ttl" /collection/$u/members/$i/fcr:metadata
            #ins=$(cat $s - <<< "} where {}" | sed -e 's|@prefix\(.*\)\.$|PREFIX \1|' -e 's|<>|insert { <>|g' | tr -d '\n')
            #$fin http patch -t "$ins" $n/fcr:metadata
        fi
    done
}

add_amerine() {
    local d i mime s
    for f in `find collection/amerine-example -type f -name full.jpg`; do
        d=`dirname $f`;
        i=$(basename $d);
        mime=`file --mime-type -b $f`;
        s=$d/metadata.ttl
        $fin http put -@ $f -H "Content-Type:$mime" /collection/amerine-example/members/$i;
        if [[ -f $s ]] ; then
            ttl=$(sed -e "s|<>|<$R/collection/amerine-example/members/$i>|g" < $s | tr -d '\n')
            $fin http put $opts --prefix wdt=http://www.wikidata.org/prop/direct/ --prefix w=http://library.ucdavis.edu/wine/ -H prefer:return=minimal -t "$ttl" /collection/amerine-example/members/$i/fcr:metadata
            #ins=$(cat $s - <<< "} where {}" | sed -e 's|@prefix\(.*\)\.$|PREFIX \1|' -e 's|<>|insert { <>|g' | tr -d '\n')
            #$fin http patch -t "$ins" $n/fcr:metadata
        fi

done

}

#main() {
    OPTS=`getopt -o P: --long do:,delete,fin:,print: -n 'initialize [options]' -- initialize "$@"` 
    if [ $? != 0 ] ; then echo "Bad initialize options." >&2 ; exit 1 ; fi
    eval set -- "$OPTS"
    do='sys,users,collections,eastman,amerine'
    delete=
    print='-P Hhb'
    #fin='node /home/quinn/fin-cli/lib -P Hhb'
    fin=fin
    # This is the default location for the acl parameters
    R=`jq -r .basePath < ~/.fccli`
    opts="--prefix fin=http://fin.library.ucdavis.edu/ --prefix user=http://fin.library.ucdavis.edu/user/ --prefix root=$R/"

    while true; do
        case $1 in
        --fin) fin=$2; shift 2;;
        --do) do=$2; shift;;
        --delete) delete=1; shift;;
        -P | --print) print="-P $2"; shift 2;;
        *) break;;
        esac
    done
    # Add print
    opts="$opts $print"

    if [[ `grep sys <<< $do` ]]; then 
        if [[ -n $delete ]]; then 
            fin_delete --tombstone /.acl
        fi
        $fin http put $opts -H prefer:return=minimal -@ root.ttl /
        acl_create --dir=/ --default --label="System Access Control"
    fi

    # Now make a users area
    if [[ `grep users <<< $do` ]]; then
        if [[ -n $delete ]]; then
            fin_delete --tombstone /user
        fi
        fin_mkdir --relation=fin:hasUser --resource="<$R>" /user
        for u in user/*; do 
            add_user `basename $u`
            # Add in a picture if it exists
            if [[ -f $u/picture.jpg ]]; then
                # This should be a fin cp command
                $fin http put $u/picture -@ $u/picture.jpg -H Content-Type:image/jpeg
            fi
        done
    fi

    # Now  we can make the groups
    if [[ `grep collections <<< $do` ]]; then
        if [[ -n $delete ]]; then
            fin_delete --tombstone /collection
        fi
        fin_mkdir --relation=pcdm:hasMember --resource="<$R>" /collection
        for u in collection/*; do 
            add_group `basename $u` $u/index.ttl
        done    
    fi

# Eastman Example
if [[ `grep eastman <<< $do` ]]; then
    if [[ -n $delete ]]; then
        fin_delete --tombstone /collection/eastman-example/members
        fin_mkdir --relation=pcdm:hasMember --resource="<$R/collection/eastman-example>" /collection/eastman-example/members
    fi
    add_eastman;
fi

# Eastman Example
if [[ `grep amerine <<< $do` ]]; then
    if [[ -n $delete ]]; then
        fin_delete --tombstone /collection/amerine-example/members
        fin_mkdir --relation=pcdm:hasMember --resource="<$R/collection/amerine-example>" /collection/amerine-example/members
    fi
    add_amerine;
fi

